export const products = [
  {
    image: "https://m.media-amazon.com/images/I/61ll2EiLAJL._AC_UL320_.jpg",
    title: "Product 1",
    description: "Description for Product 1.",
    price: "$0.00",
    slug: "product-1",
  },
  {
    image: "https://m.media-amazon.com/images/I/615mJs9XccL._AC_UL320_.jpg",
    title: "Product 2",
    description: "Description for Product 2.",
    price: "$0.00",
    slug: "product-2",
  },
  {
    image: "https://m.media-amazon.com/images/I/510ui3CBLbL._AC_UL320_.jpg",
    title: "Product 3",
    description: "Description for Product 3.",
    price: "$0.00",
    slug: "product-3",
  },
  {
    image: "https://m.media-amazon.com/images/I/61qsUDP+WuL._AC_UL320_.jpg",
    title: "Product 4",
    description: "Description for Product 4.",
    price: "$0.00",
    slug: "product-4",
  },
  {
    image: "https://m.media-amazon.com/images/I/718tWBNNfkL._AC_UL320_.jpg",
    title: "Product 5",
    description: "Description for Product 5.",
    price: "$0.00",
    slug: "product-5",
  },
  {
    image: "https://m.media-amazon.com/images/I/718tWBNNfkL._AC_UL320_.jpg",
    title: "Product 6",
    description: "Description for Product 6.",
    price: "$0.00",
    slug: "product-6",
  },
  {
    image: "https://m.media-amazon.com/images/I/7151rsGhpkL._AC_UL320_.jpg",
    title: "Product 7",
    description: "Description for Product 7.",
    price: "$0.00",
    slug: "product-7",
  },
  {
    image: "https://m.media-amazon.com/images/I/61MSABGkBKL._AC_UL320_.jpg",
    title: "Product 8",
    description: "Description for Product 8.",
    price: "$0.00",
    slug: "product-8",
  },
  {
    image: "https://m.media-amazon.com/images/I/71PYCZfZ2BL._AC_UL320_.jpg",
    title: "Product 9",
    description: "Description for Product 9.",
    price: "$0.00",
    slug: "product-9",
  },
  {
    image: "https://m.media-amazon.com/images/I/91D+7LuTsQL._AC_UL320_.jpg",
    title: "Product 10",
    description: "Description for Product 10.",
    price: "$0.00",
    slug: "product-10",
  },
  {
    image: "https://m.media-amazon.com/images/I/61PuOA7jGiL._AC_UL320_.jpg",
    title: "Product 11",
    description: "Description for Product 11.",
    price: "$0.00",
    slug: "product-11",
  },
  {
    image: "https://m.media-amazon.com/images/I/61PK-OTlOdL._AC_UL320_.jpg",
    title: "Product 12",
    description: "Description for Product 12.",
    price: "$0.00",
    slug: "product-12",
  },
  {
    image: "https://m.media-amazon.com/images/I/61IrwxMbtPL._AC_UL320_.jpg",
    title: "Product 13",
    description: "Description for Product 13.",
    price: "$0.00",
    slug: "product-13",
  },
  {
    image: "https://m.media-amazon.com/images/I/81vwGq+i7iL._AC_UL320_.jpg",
    title: "Product 14",
    description: "Description for Product 14.",
    price: "$0.00",
    slug: "product-14",
  },
  {
    image: "https://m.media-amazon.com/images/I/71UwwRFL0rL._AC_UL320_.jpg",
    title: "Product 15",
    description: "Description for Product 15.",
    price: "$0.00",
    slug: "product-15",
  },
  {
    image: "https://m.media-amazon.com/images/I/71vja1k7ywL._AC_UL320_.jpg",
    title: "Product 16",
    description: "Description for Product 16.",
    price: "$0.00",
    slug: "product-16",
  },
];
